tags:
  - id: 0
    position: [0.0, 0.0, 1.5]            # x, y, z in meters
    orientation_rpy: [0.0, 0.0, 1.5708]  # roll, pitch, yaw in radians
  - id: 1
    position: [1.0, 0.0, 1.5]
    orientation_rpy: [0.0, 0.0, 1.5708]
